### ISSUE TITLE
Share the position of the car

### ISSUE THREAD

**Issue by ObaidaHanteer** [FamilyParking/Project#19]
We want to allow people to share their car position only pushing a button

Requires: Google Maps API, Server communication, Mail sending
Time Estimation: 60 hours

**Comment by gioramponi** [comment]
We want to allow people to share their car position only pushing a button
- Requires: Google Maps API, Server communication, Mail sending
- Time Estimation:  60 hours

**Comment by fnobilia** [comment]
Done
