### ISSUE TITLE
Insert member by android contacts

### ISSUE THREAD

**Issue by mauropv** [FamilyParking/Project#3]
Allow users to search in their contacts list and add members to groups

**Comment by fnobilia** [comment]
Solved!

**Comment by fnobilia** [comment]
We implement the code to add contacts inside only one group. Still there is no way to create different groups.

**Comment by ObaidaHanteer** [comment]
But According to the first presentation feedback, we don't need to create more than one group in our scenario. It is only one default group which represents the family and you add members to it. 
We are not interested in sharing the car with different types of groups now.
